// Generated by gencpp from file lotti_nav/WhereIgoRequest.msg
// DO NOT EDIT!


#ifndef LOTTI_NAV_MESSAGE_WHEREIGOREQUEST_H
#define LOTTI_NAV_MESSAGE_WHEREIGOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lotti_nav
{
template <class ContainerAllocator>
struct WhereIgoRequest_
{
  typedef WhereIgoRequest_<ContainerAllocator> Type;

  WhereIgoRequest_()
    : request(0)  {
    }
  WhereIgoRequest_(const ContainerAllocator& _alloc)
    : request(0)  {
  (void)_alloc;
    }



   typedef int64_t _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::lotti_nav::WhereIgoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lotti_nav::WhereIgoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WhereIgoRequest_

typedef ::lotti_nav::WhereIgoRequest_<std::allocator<void> > WhereIgoRequest;

typedef boost::shared_ptr< ::lotti_nav::WhereIgoRequest > WhereIgoRequestPtr;
typedef boost::shared_ptr< ::lotti_nav::WhereIgoRequest const> WhereIgoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lotti_nav::WhereIgoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lotti_nav::WhereIgoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lotti_nav::WhereIgoRequest_<ContainerAllocator1> & lhs, const ::lotti_nav::WhereIgoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lotti_nav::WhereIgoRequest_<ContainerAllocator1> & lhs, const ::lotti_nav::WhereIgoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lotti_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lotti_nav::WhereIgoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lotti_nav::WhereIgoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lotti_nav::WhereIgoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lotti_nav::WhereIgoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lotti_nav::WhereIgoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lotti_nav::WhereIgoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lotti_nav::WhereIgoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b8b3e2da8be658e01dee48451dead03";
  }

  static const char* value(const ::lotti_nav::WhereIgoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b8b3e2da8be658eULL;
  static const uint64_t static_value2 = 0x01dee48451dead03ULL;
};

template<class ContainerAllocator>
struct DataType< ::lotti_nav::WhereIgoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lotti_nav/WhereIgoRequest";
  }

  static const char* value(const ::lotti_nav::WhereIgoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lotti_nav::WhereIgoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 request\n"
;
  }

  static const char* value(const ::lotti_nav::WhereIgoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lotti_nav::WhereIgoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WhereIgoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lotti_nav::WhereIgoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lotti_nav::WhereIgoRequest_<ContainerAllocator>& v)
  {
    s << indent << "request: ";
    Printer<int64_t>::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOTTI_NAV_MESSAGE_WHEREIGOREQUEST_H
