// Generated by gencpp from file lotti_nav/WhereIgoResponse.msg
// DO NOT EDIT!


#ifndef LOTTI_NAV_MESSAGE_WHEREIGORESPONSE_H
#define LOTTI_NAV_MESSAGE_WHEREIGORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lotti_nav
{
template <class ContainerAllocator>
struct WhereIgoResponse_
{
  typedef WhereIgoResponse_<ContainerAllocator> Type;

  WhereIgoResponse_()
    : destination()  {
    }
  WhereIgoResponse_(const ContainerAllocator& _alloc)
    : destination(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _destination_type;
  _destination_type destination;





  typedef boost::shared_ptr< ::lotti_nav::WhereIgoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lotti_nav::WhereIgoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WhereIgoResponse_

typedef ::lotti_nav::WhereIgoResponse_<std::allocator<void> > WhereIgoResponse;

typedef boost::shared_ptr< ::lotti_nav::WhereIgoResponse > WhereIgoResponsePtr;
typedef boost::shared_ptr< ::lotti_nav::WhereIgoResponse const> WhereIgoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lotti_nav::WhereIgoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lotti_nav::WhereIgoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lotti_nav::WhereIgoResponse_<ContainerAllocator1> & lhs, const ::lotti_nav::WhereIgoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.destination == rhs.destination;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lotti_nav::WhereIgoResponse_<ContainerAllocator1> & lhs, const ::lotti_nav::WhereIgoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lotti_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lotti_nav::WhereIgoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lotti_nav::WhereIgoResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lotti_nav::WhereIgoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lotti_nav::WhereIgoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lotti_nav::WhereIgoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lotti_nav::WhereIgoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lotti_nav::WhereIgoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e47796db9d7d90bff30cd181ffc714b";
  }

  static const char* value(const ::lotti_nav::WhereIgoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e47796db9d7d90bULL;
  static const uint64_t static_value2 = 0xff30cd181ffc714bULL;
};

template<class ContainerAllocator>
struct DataType< ::lotti_nav::WhereIgoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lotti_nav/WhereIgoResponse";
  }

  static const char* value(const ::lotti_nav::WhereIgoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lotti_nav::WhereIgoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string destination\n"
"\n"
"\n"
;
  }

  static const char* value(const ::lotti_nav::WhereIgoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lotti_nav::WhereIgoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.destination);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WhereIgoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lotti_nav::WhereIgoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lotti_nav::WhereIgoResponse_<ContainerAllocator>& v)
  {
    s << indent << "destination: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.destination);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOTTI_NAV_MESSAGE_WHEREIGORESPONSE_H
