// Generated by gencpp from file lotti_nav/WhereIgo.msg
// DO NOT EDIT!


#ifndef LOTTI_NAV_MESSAGE_WHEREIGO_H
#define LOTTI_NAV_MESSAGE_WHEREIGO_H

#include <ros/service_traits.h>


#include <lotti_nav/WhereIgoRequest.h>
#include <lotti_nav/WhereIgoResponse.h>


namespace lotti_nav
{

struct WhereIgo
{

typedef WhereIgoRequest Request;
typedef WhereIgoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WhereIgo
} // namespace lotti_nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lotti_nav::WhereIgo > {
  static const char* value()
  {
    return "bf1cfd8512ed73dbf0bc8ba1f3b6fab3";
  }

  static const char* value(const ::lotti_nav::WhereIgo&) { return value(); }
};

template<>
struct DataType< ::lotti_nav::WhereIgo > {
  static const char* value()
  {
    return "lotti_nav/WhereIgo";
  }

  static const char* value(const ::lotti_nav::WhereIgo&) { return value(); }
};


// service_traits::MD5Sum< ::lotti_nav::WhereIgoRequest> should match
// service_traits::MD5Sum< ::lotti_nav::WhereIgo >
template<>
struct MD5Sum< ::lotti_nav::WhereIgoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lotti_nav::WhereIgo >::value();
  }
  static const char* value(const ::lotti_nav::WhereIgoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lotti_nav::WhereIgoRequest> should match
// service_traits::DataType< ::lotti_nav::WhereIgo >
template<>
struct DataType< ::lotti_nav::WhereIgoRequest>
{
  static const char* value()
  {
    return DataType< ::lotti_nav::WhereIgo >::value();
  }
  static const char* value(const ::lotti_nav::WhereIgoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lotti_nav::WhereIgoResponse> should match
// service_traits::MD5Sum< ::lotti_nav::WhereIgo >
template<>
struct MD5Sum< ::lotti_nav::WhereIgoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lotti_nav::WhereIgo >::value();
  }
  static const char* value(const ::lotti_nav::WhereIgoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lotti_nav::WhereIgoResponse> should match
// service_traits::DataType< ::lotti_nav::WhereIgo >
template<>
struct DataType< ::lotti_nav::WhereIgoResponse>
{
  static const char* value()
  {
    return DataType< ::lotti_nav::WhereIgo >::value();
  }
  static const char* value(const ::lotti_nav::WhereIgoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOTTI_NAV_MESSAGE_WHEREIGO_H
